[build]
  publish = "public"
  command = "npm install"

# Serve index.html at /
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Redirect non-existent routes to login.html (optional)
[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 404

# Optional: force redirect for specific paths
[[redirects]]
  from = "/admin-librarian/login.html"
  to = "/login.html"
  status = 301
  force = true