[build]
  base = ""
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200
  force = false

[[redirects]]
  from = "/admin-librarian/login.html"
  to = "/login.html"
  status = 301
  force = true